# Generated by Django 6.0.7 on 2026-08-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тура')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (латиницей)')),
                ('category', models.CharField(choices=[('budget', 'Бюджет'), ('standard', 'Стандарт'), ('premium', 'Премиум')], default='standard', max_length=20, verbose_name='Категория')),
                ('direction', models.CharField(blank=True, max_length=200, verbose_name='Направление')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Длительность (дней)')),
                ('season', models.CharField(blank=True, max_length=100, verbose_name='Сезон')),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена от ($)')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Главное фото')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
