# Generated by Django 6.0.7 on 2026-08-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('cultural', 'Культурный'), ('adventure', 'Приключенческий'), ('historical', 'Исторический'), ('mice', 'MICE / Деловой'), ('individual', 'Индивидуальный'), ('photo', 'Фототур')], default='cultural', max_length=20, verbose_name='Тип туризма'),
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='День №')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок дня')),
                ('description', models.TextField(blank=True, verbose_name='Описание дня')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tourism.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'День программы',
                'verbose_name_plural': 'Программа по дням',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фото тура',
                'verbose_name_plural': 'Фотогалерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TourInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('is_included', models.BooleanField(default=True, verbose_name='Включено в тур?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='tourism.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Пункт (включено/нет)',
                'verbose_name_plural': 'Включено / Не включено',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TourPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('budget', 'Бюджет'), ('standard', 'Стандарт'), ('premium', 'Премиум')], default='standard', max_length=20, verbose_name='Категория')),
                ('season', models.CharField(choices=[('low', 'Низкий сезoн'), ('high', 'Высокий сезон'), ('all', 'Круглый год')], default='all', max_length=10, verbose_name='Сезон')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена ($)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tourism.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены (категория + сезон)',
                'ordering': ['category', 'season'],
            },
        ),
    ]
