# Generated by Django 6.0.7 on 2026-08-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_tour_tour_type_tourday_tourimage_tourinclude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(help_text='Например: Класс отеля, Питание, Тип группы, Трансфер', max_length=200, verbose_name='Особенность')),
                ('budget', models.CharField(blank=True, help_text='Например: Отель 3*. Оставь пустым если НЕ входит', max_length=200, verbose_name='Бюджет')),
                ('standard', models.CharField(blank=True, help_text='Например: Отель 4*', max_length=200, verbose_name='Стандарт')),
                ('premium', models.CharField(blank=True, help_text='Например: Отель 5*', max_length=200, verbose_name='Премиум')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_features', to='tourism.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Особенность категории',
                'verbose_name_plural': 'Сравнение категорий (Бюджет/Стандарт/Премиум)',
                'ordering': ['order'],
            },
        ),
    ]
