# Generated by Django 6.0.7 on 2026-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_categoryfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='season_autumn',
            field=models.BooleanField(default=True, verbose_name='🍂 Осень'),
        ),
        migrations.AddField(
            model_name='tour',
            name='season_spring',
            field=models.BooleanField(default=True, verbose_name='🌷 Весна'),
        ),
        migrations.AddField(
            model_name='tour',
            name='season_summer',
            field=models.BooleanField(default=True, verbose_name='☀️ Лето'),
        ),
        migrations.AddField(
            model_name='tour',
            name='season_winter',
            field=models.BooleanField(default=True, verbose_name='❄️ Зима'),
        ),
    ]
