# Generated by Django 6.0.7 on 2026-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_tour_season_autumn_tour_season_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('cultural', 'Культурный'), ('historical', 'Исторический'), ('individual', 'Частный')], default='cultural', max_length=20, verbose_name='Тип туризма'),
        ),
    ]
