# Generated by Django 6.0.7 on 2026-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название кейса')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (латиницей)')),
                ('direction', models.CharField(choices=[('tourism', 'Туризм'), ('consulting', 'Консалтинг'), ('linguistics', 'Лингвистика')], default='tourism', max_length=20, verbose_name='Направление')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Клиент')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('result', models.CharField(blank=True, max_length=300, verbose_name='Результат')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Фото')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
